-- Schema snapshot reconstructed from source Supabase OpenAPI
create extension if not exists citext;

create table if not exists public.records (
  id bigint generated by default as identity primary key,
  name text not null,
  timestamp text,
  summary text,
  extracted_text text,
  pdf_url text not null,
  volume text,
  number text,
  title_name text,
  page_numbers text,
  authors text,
  language text,
  email text,
  creator_name text,
  conclusion text,
  pdf_public_id text
);

create table if not exists public.tags (
  id integer generated by default as identity primary key,
  name text not null,
  created_at timestamptz default CURRENT_TIMESTAMP,
  important boolean default false
);

create table if not exists public.authors (
  id bigint generated by default as identity primary key,
  name citext not null,
  created_at timestamptz default now(),
  description text,
  cover_url text,
  national text,
  designation text,
  short_name text
);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text,
  name text,
  confirmed boolean default false,
  work_done boolean default false
);

create table if not exists public.record_authors (
  record_id bigint references public.records (id) on delete cascade,
  author_id bigint references public.authors (id) on delete cascade,
  created_at timestamptz default now(),
  primary key (record_id, author_id)
);

create table if not exists public.record_tags (
  record_id bigint references public.records (id) on delete cascade,
  tag_id integer references public.tags (id) on delete cascade,
  created_at timestamptz default CURRENT_TIMESTAMP,
  primary key (record_id, tag_id)
);

create table if not exists public.summaries (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  summary text,
  record_id bigint references public.records (id) on delete cascade,
  email text,
  name text
);

create table if not exists public.conclusions (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  conclusion text,
  record_id bigint references public.records (id) on delete cascade,
  email text,
  name text
);

create or replace function public.reset_identity(p_table text, p_column text default 'id')
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  seq text;
  max_id bigint;
begin
  select pg_get_serial_sequence(format('%I.%I', 'public', p_table), p_column) into seq;
  if seq is null then
    return null;
  end if;

  execute format('select max(%I) from %I.%I', p_column, 'public', p_table) into max_id;
  if max_id is null then
    max_id := 0;
  end if;

  execute format('select setval(%L, %s)', seq, max_id);
  return max_id;
end;
$$;
